"""005_payment_method_accepted_difference

Revision ID: 379ca4b050c0
Revises: 627d1be90d54
Create Date: 2026-04-06 18:45:21.110333
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '379ca4b050c0'
down_revision: Union[str, None] = '627d1be90d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingreso_items_ingreso_id'), table_name='ingreso_items')
    op.drop_index(op.f('ix_ingreso_items_variant_id'), table_name='ingreso_items')
    op.drop_index(op.f('ix_ingresos_company_date'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_company_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_company_status'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_created_by_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_date'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_provider_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_status'), table_name='ingresos')
    op.drop_index(op.f('ix_locals_company_id'), table_name='locals')
    op.drop_index(op.f('ix_locals_is_active'), table_name='locals')
    payment_method_enum = sa.Enum('TRANSFERENCIA', 'CHEQUE', 'EFECTIVO', 'DEPOSITO', 'DEBITO_DIRECTO', 'OTRO', name='payment_method')
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('payment_vouchers', sa.Column('payment_method', payment_method_enum, nullable=True))
    op.add_column('payment_vouchers', sa.Column('due_date', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_pedido_items_pedido_id'), table_name='pedido_items')
    op.drop_index(op.f('ix_pedido_items_variant_id'), table_name='pedido_items')
    op.drop_index(op.f('ix_pedidos_company_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_company_status'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_date'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_provider_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_status'), table_name='pedidos')
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_is_active'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_stock'), table_name='product_variants')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_company_brand'), table_name='products')
    op.drop_index(op.f('ix_products_company_category'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_providers_company_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_is_active'), table_name='providers')
    op.add_column('purchase_orders', sa.Column('accepted_difference', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('purchase_orders', sa.Column('accepted_difference_obs', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_sale_items_sale_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_variant_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sales_company_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_company_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_company_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_local_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_type'), table_name='sales')
    op.drop_index(op.f('ix_stock_movements_company_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_by_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_variant_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_variant_id'), 'stock_movements', ['variant_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_type'), 'stock_movements', ['type'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_by_id'), 'stock_movements', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_company_id'), 'stock_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_type'), 'sales', ['type'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_index(op.f('ix_sales_local_id'), 'sales', ['local_id'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index(op.f('ix_sales_company_status'), 'sales', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_sales_company_id'), 'sales', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_company_date'), 'sales', ['company_id', 'date'], unique=False)
    op.create_index(op.f('ix_sale_items_variant_id'), 'sale_items', ['variant_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_id'), 'sale_items', ['sale_id'], unique=False)
    op.drop_column('purchase_orders', 'accepted_difference_obs')
    op.drop_column('purchase_orders', 'accepted_difference')
    op.create_index(op.f('ix_providers_is_active'), 'providers', ['is_active'], unique=False)
    op.create_index(op.f('ix_providers_company_id'), 'providers', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_company_category'), 'products', ['company_id', 'category'], unique=False)
    op.create_index(op.f('ix_products_company_brand'), 'products', ['company_id', 'brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_product_variants_stock'), 'product_variants', ['stock'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_is_active'), 'product_variants', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=False)
    op.create_index(op.f('ix_pedidos_status'), 'pedidos', ['status'], unique=False)
    op.create_index(op.f('ix_pedidos_provider_id'), 'pedidos', ['provider_id'], unique=False)
    op.create_index(op.f('ix_pedidos_date'), 'pedidos', ['date'], unique=False)
    op.create_index(op.f('ix_pedidos_company_status'), 'pedidos', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_pedidos_company_id'), 'pedidos', ['company_id'], unique=False)
    op.create_index(op.f('ix_pedido_items_variant_id'), 'pedido_items', ['variant_id'], unique=False)
    op.create_index(op.f('ix_pedido_items_pedido_id'), 'pedido_items', ['pedido_id'], unique=False)
    op.drop_column('payment_vouchers', 'due_date')
    op.drop_column('payment_vouchers', 'payment_method')
    sa.Enum(name='payment_method').drop(op.get_bind(), checkfirst=True)
    op.create_index(op.f('ix_locals_is_active'), 'locals', ['is_active'], unique=False)
    op.create_index(op.f('ix_locals_company_id'), 'locals', ['company_id'], unique=False)
    op.create_index(op.f('ix_ingresos_status'), 'ingresos', ['status'], unique=False)
    op.create_index(op.f('ix_ingresos_provider_id'), 'ingresos', ['provider_id'], unique=False)
    op.create_index(op.f('ix_ingresos_date'), 'ingresos', ['date'], unique=False)
    op.create_index(op.f('ix_ingresos_created_by_id'), 'ingresos', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_ingresos_company_status'), 'ingresos', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_ingresos_company_id'), 'ingresos', ['company_id'], unique=False)
    op.create_index(op.f('ix_ingresos_company_date'), 'ingresos', ['company_id', 'date'], unique=False)
    op.create_index(op.f('ix_ingreso_items_variant_id'), 'ingreso_items', ['variant_id'], unique=False)
    op.create_index(op.f('ix_ingreso_items_ingreso_id'), 'ingreso_items', ['ingreso_id'], unique=False)
    # ### end Alembic commands ###
