"""004_add_procurement_support_models

Revision ID: 627d1be90d54
Revises: 8409976b7861
Create Date: 2026-03-31 16:50:24.508581
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '627d1be90d54'
down_revision: Union[str, None] = '8409976b7861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('days_max_sin_rv', sa.Integer(), nullable=False),
    sa.Column('days_max_sin_confirmacion', sa.Integer(), nullable=False),
    sa.Column('days_max_sin_pago', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=200), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(length=200), nullable=True),
    sa.Column('smtp_password', sa.String(length=500), nullable=True),
    sa.Column('smtp_from', sa.String(length=200), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_mail_configs_company_id')
    )
    op.create_table('transports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('cbu', sa.String(length=22), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanban_boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_vouchers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('POR_PAGAR', 'PARCIAL', 'PAGADO', 'VENCIDO', 'ANULADO', name='payment_status', create_constraint=True), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_iibb', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_ganancias', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_suss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pdf_file', sa.String(length=500), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_list_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Enum('PRECOMPRA', 'REPOSICION', 'CAMBIO', name='purchase_order_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('BORRADOR', 'ENVIADO', 'RECIBIDO', 'COMPLETADO', 'ANULADO', name='purchase_order_status', create_constraint=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('total_ordered', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_received', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('excel_file', sa.String(length=500), nullable=True),
    sa.Column('pdf_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locals.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanban_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['kanban_boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price_list_file_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_list_file_id'], ['price_list_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('FACTURA', 'REMITO', 'REMITO_FACTURA', name='purchase_invoice_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'VERDE', 'ROJO', 'ALERTA_REPO', 'ANULADO', name='purchase_invoice_status', create_constraint=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remito_venta_number', sa.String(length=100), nullable=True),
    sa.Column('linked_to_id', sa.Integer(), nullable=True),
    sa.Column('pdf_file', sa.String(length=500), nullable=True),
    sa.Column('pdf_parsed', sa.Boolean(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('local_obs', sa.Text(), nullable=True),
    sa.Column('compras_obs', sa.Text(), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('ingreso_status', sa.Enum('PENDIENTE', 'PARCIAL', 'COMPLETO', 'NO', name='purchase_invoice_ingreso_status', create_constraint=True), nullable=False),
    sa.Column('ingreso_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingreso_photo', sa.String(length=500), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_to_id'], ['purchase_invoices.id'], ),
    sa.ForeignKeyConstraint(['local_id'], ['locals.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanban_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='kanbancardpriority', create_constraint=True), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('image_file', sa.String(length=500), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['column_id'], ['kanban_columns.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('INFO', 'ALERTA', 'URGENTE', name='notificationtype', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('LEIDA', 'NO_LEIDA', name='notificationstatus', create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('to_role', sa.String(length=30), nullable=True),
    sa.Column('related_invoice_id', sa.Integer(), nullable=True),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['purchase_invoices.id'], ),
    sa.ForeignKeyConstraint(['related_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_invoice_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_voucher_id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_voucher_id'], ['payment_vouchers.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_invoice_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('quantity_invoiced', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('sender', sa.String(length=200), nullable=True),
    sa.Column('destination_local_id', sa.Integer(), nullable=True),
    sa.Column('date_sent', sa.Date(), nullable=True),
    sa.Column('date_arrived', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image_file', sa.String(length=500), nullable=True),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_local_id'], ['locals.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Extend user_role enum with new roles
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'SUPERVISOR'")
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'MONITOREO'")
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'TRANSPORTE'")

    # Add Tango/fiscal fields to providers
    op.add_column('providers', sa.Column('legal_name', sa.String(length=300), nullable=True))
    op.add_column('providers', sa.Column('tax_id_type', sa.String(length=20), nullable=True))
    op.add_column('providers', sa.Column('tax_condition', sa.String(length=50), nullable=True))
    op.add_column('providers', sa.Column('gross_income', sa.String(length=50), nullable=True))
    op.add_column('providers', sa.Column('domicilio', sa.String(length=500), nullable=True))
    op.add_column('providers', sa.Column('cp', sa.String(length=10), nullable=True))
    op.add_column('providers', sa.Column('localidad', sa.String(length=100), nullable=True))
    op.add_column('providers', sa.Column('provincia', sa.String(length=100), nullable=True))
    op.add_column('providers', sa.Column('pais', sa.String(length=50), nullable=True))
    op.add_column('providers', sa.Column('vendor_name', sa.String(length=200), nullable=True))
    op.add_column('providers', sa.Column('fax', sa.String(length=50), nullable=True))
    op.add_column('providers', sa.Column('ret_iva_pct', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('providers', sa.Column('ret_iibb_pct', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('providers', sa.Column('ret_ganancias_pct', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('providers', sa.Column('ret_suss_pct', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('providers', sa.Column('days_alert_sin_rv', sa.Integer(), nullable=True))
    op.add_column('providers', sa.Column('logo_filename', sa.String(length=500), nullable=True))
    op.add_column('providers', sa.Column('tango_code', sa.String(length=50), nullable=True))
    op.add_column('providers', sa.Column('order_prefix', sa.String(length=20), nullable=True))

    # Add local_id to users
    op.add_column('users', sa.Column('local_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_local_id', 'users', 'locals', ['local_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_local_id', 'users', type_='foreignkey')
    op.drop_column('users', 'local_id')
    op.drop_column('providers', 'order_prefix')
    op.drop_column('providers', 'tango_code')
    op.drop_column('providers', 'logo_filename')
    op.drop_column('providers', 'days_alert_sin_rv')
    op.drop_column('providers', 'ret_suss_pct')
    op.drop_column('providers', 'ret_ganancias_pct')
    op.drop_column('providers', 'ret_iibb_pct')
    op.drop_column('providers', 'ret_iva_pct')
    op.drop_column('providers', 'fax')
    op.drop_column('providers', 'vendor_name')
    op.drop_column('providers', 'pais')
    op.drop_column('providers', 'provincia')
    op.drop_column('providers', 'localidad')
    op.drop_column('providers', 'cp')
    op.drop_column('providers', 'domicilio')
    op.drop_column('providers', 'gross_income')
    op.drop_column('providers', 'tax_condition')
    op.drop_column('providers', 'tax_id_type')
    op.drop_column('providers', 'legal_name')
    op.drop_table('shipments')
    op.drop_table('purchase_invoice_items')
    op.drop_table('payment_invoice_links')
    op.drop_table('notifications')
    op.drop_table('kanban_cards')
    op.drop_table('purchase_order_items')
    op.drop_table('purchase_invoices')
    op.drop_table('price_list_items')
    op.drop_table('kanban_columns')
    op.drop_table('purchase_orders')
    op.drop_table('price_list_files')
    op.drop_table('payment_vouchers')
    op.drop_table('kanban_boards')
    op.drop_table('credit_notes')
    op.drop_table('audit_logs')
    op.drop_table('provider_contacts')
    op.drop_table('bank_accounts')
    op.drop_table('transports')
    op.drop_table('mail_configs')
    # Note: PostgreSQL enum values cannot be removed, so SUPERVISOR/MONITOREO/TRANSPORTE remain
    # ### end Alembic commands ###
