"""add_pc_licenses

Revision ID: dc73d4b3cbb3
Revises: a91c84b89a81
Create Date: 2026-04-14 16:48:38.632405
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'dc73d4b3cbb3'
down_revision: Union[str, None] = 'a91c84b89a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'pc_licenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=64), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(length=200), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('machine_id', sa.String(length=300), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('activated_at', sa.DateTime(), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(), nullable=True),
        sa.Column('deactivated_reason', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key'),
    )
    op.create_index(op.f('ix_pc_licenses_id'), 'pc_licenses', ['id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_pc_licenses_id'), table_name='pc_licenses')
    op.drop_table('pc_licenses')

    op.drop_index(op.f('ix_notification_device_id'), table_name='notifications')
    op.drop_index(op.f('ix_notification_sync_event'), table_name='notifications')
    op.drop_index(op.f('ix_pv_company_status'), table_name='payment_vouchers')
    op.drop_index(op.f('ix_pv_provider'), table_name='payment_vouchers')
    op.alter_column('pedidos', 'expected_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_prov_company_active'), table_name='providers')
    op.drop_index(op.f('ix_pi_company_status'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_pi_order_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_pi_provider_company'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_po_company_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_po_date'), table_name='purchase_orders')
    op.drop_index(op.f('ix_po_local_company'), table_name='purchase_orders')
    op.drop_index(op.f('ix_po_provider_company'), table_name='purchase_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_po_provider_company'), 'purchase_orders', ['provider_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_po_local_company'), 'purchase_orders', ['local_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_po_date'), 'purchase_orders', ['date'], unique=False)
    op.create_index(op.f('ix_po_company_status'), 'purchase_orders', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_pi_provider_company'), 'purchase_invoices', ['provider_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_pi_order_id'), 'purchase_invoices', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_pi_company_status'), 'purchase_invoices', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_prov_company_active'), 'providers', ['company_id', 'is_active'], unique=False)
    op.alter_column('pedidos', 'expected_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_pv_provider'), 'payment_vouchers', ['provider_id'], unique=False)
    op.create_index(op.f('ix_pv_company_status'), 'payment_vouchers', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_notification_sync_event'), 'notifications', ['related_sync_event_id'], unique=False)
    op.create_index(op.f('ix_notification_device_id'), 'notifications', ['device_id'], unique=False)
    op.create_table('import_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('referencia', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('tipo', postgresql.ENUM('MARITIMO', 'AEREO', 'TERRESTRE', name='import_order_type'), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('BORRADOR', 'CONFIRMADO', 'EMBARCADO', 'EN_TRANSITO', 'EN_ADUANA', 'DISPONIBLE', 'ANULADO', name='import_order_status'), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pais_origen', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ciudad_origen', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('puerto_origen', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('puerto_destino', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('incoterm', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('numero_bl', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numero_factura_proveedor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numero_dua', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fecha_orden', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_embarque', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_eta', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_arribo_real', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_despacho_aduana', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_disponible', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valor_fob_usd', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('flete_usd', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('seguro_usd', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('otros_gastos_usd', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('tipo_cambio', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('derechos_aduana_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('iva_importacion_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('estadistica_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('percepciones_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('honorarios_despachante_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('otros_costos_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_unidades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('costo_landing_total_usd', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('costo_unit_usd', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('liquidacion_confirmada', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('import_orders_company_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('import_orders_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('import_orders_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('import_orders_pkey'))
    )
    op.create_table('import_order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('import_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codigo_comercial', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion_comercial', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('posicion_arancelaria', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio_unitario_usd', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('subtotal_usd', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('costo_landing_unit_usd', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['import_order_id'], ['import_orders.id'], name=op.f('import_order_items_import_order_id_fkey')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('import_order_items_variant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('import_order_items_pkey'))
    )
    # ### end Alembic commands ###
